web:
  build: .
  environment:
    PORT: 80
    DATABASE_URL: ecto://newspacks:4qKbOKsNo2sK28HcwgapsQTzzLU_pg@db/newspacks_prod
  ports:
    - 80:80
  links:
    - db
db:
  image: postgres:9.4
  environment:
    POSTGRES_USER: newspacks
    POSTGRES_PASSWORD: '4qKbOKsNo2sK28HcwgapsQTzzLU_'

